### PR TITLE
Update hello.txt

### PR DESCRIPTION
**Pull request by bbsbldcq3**
啊哈！可以了

### CODE REVIEW

**Comment by bbsbldcq** [comment]
你好!

**Comment by bbsbldcq** [comment]
再修改一下

**Comment by bbsbldcq3** [comment]
you are right!

**Comment by bbsbldcq** [comment]
yep!

**Comment by bbsbldcq3** [comment]
HHHHHHHaaaaaa

**Comment by bbsbldcq3** [comment]
dddddddd!

**Comment by bbsbldcq** [comment]
EEEEEE!!!!

**Comment by bbsbldcq3** [comment]
FFFFFFFF

**Pull request merged**
